wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.3
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1669079671.388706
    t:
      1:
      - 1
      - 9
      - 41
      - 54
      - 55
      - 80
      2:
      - 1
      - 9
      - 41
      - 54
      - 55
      - 80
      3:
      - 13
      - 16
      - 23
      4: 3.9.7
      5: 0.13.3
      8:
      - 5
datamodule/Batch Size:
  desc: null
  value: 1
datamodule/Checkpoint File:
  desc: null
  value: None
datamodule/Image Directory:
  desc: null
  value: /media/sasank/LinuxStorage/Dropbox (UFL)/Canine Kinematics Data/TPLO_Ten_Dogs_grids/
datamodule/Num Workers:
  desc: null
  value: 8
datamodule/Pin Memory:
  desc: null
  value: false
datamodule/Shuffle:
  desc: null
  value: true
datamodule/Subset Pixels:
  desc: null
  value: true
dataset/Class Labels:
  desc: null
  value:
    '0': bone
    '1': background
dataset/Image Channels:
  desc: null
  value: 1
dataset/Image Height:
  desc: null
  value: 1024
dataset/Image Threshold:
  desc: null
  value: 0
dataset/Image Width:
  desc: null
  value: 1024
dataset/Model Type:
  desc: null
  value: fem
dataset/Using Albumentations:
  desc: null
  value: true
etl/Custom Test Set:
  desc: null
  value: false
etl/Data Directory:
  desc: null
  value: data
etl/Keypoint Directory:
  desc: null
  value: keypoints
etl/Random State:
  desc: null
  value: 42
etl/Raw Data File:
  desc: null
  value: -1
etl/Test Set Name:
  desc: null
  value: /my/test/set.csv
etl/Test Size:
  desc: null
  value: 0.01
etl/Validation Size:
  desc: null
  value: 0.2
hparams/Learning_Rate:
  desc: null
  value: 0.001
hparams/Load From Checkpoint:
  desc: null
  value: false
init/Fast Dev Run:
  desc: null
  value: true
init/Max Epochs:
  desc: null
  value: 1
init/Max Steps:
  desc: null
  value: -1
init/Model Name:
  desc: null
  value: KeypointTest
init/Project Name:
  desc: null
  value: Keypoint Estimator Development!
init/Run Name:
  desc: null
  value: 2022-11-21-20-14-30
init/Strategy:
  desc: null
  value: None
init/Wandb Run Group:
  desc: null
  value: Local
'keypoint_net_module/Image Channels #':
  desc: null
  value: 1
'keypoint_net_module/Keypoints #':
  desc: null
  value: 128
transform/Transform:
  desc: null
  value: null
